Move FLAIR to resources_init & make non-en spaCy models optional
dataiku/dss-plugin-nlp-named-entity-recognition pull request #10
Opened 2022-06-05 14:42 UTC by Muennighoff

Notes

- Prior to this installation fails for Python 3.7 due to transformers rust compiler problem (Need higher transformers version)
- Prior to this Python 3.7 Flair usage fails due to outdated Pandas version
- The NumPy version pin is due to this error in Python 3.7 (https://stackoverflow.com/questions/65998646/pandas-error-for-creating-an-emptydataframe)
- Removed other versions pins as I did not find any problems leaving them as is
- Not incrementing the version yet as we may bundle this with other NER upgrades following
- spaCy: 
    - Adding a new model in requirements: **Edit requirements, update env**
    - Adding a completely new model: **Edit requirements, edit plugin.json, edit spacy_utils, update env**
- Flair:
    - Adding a new model: **Edit resources_init, edit recipe.py, update env**

Do you find a nice way to shorten any of the above for adding a new language?
Should we add the instructions to the [plugin website](https://www.dataiku.com/product/plugins/named-entity-recognition/)?

2022-06-15 17:45 UTC, amandamilberg reviewed
Tested on 

1. Python 37, could download flair model
2. Python 37, webapp working accordingly 
3. Ran NER recipe on new / old plugin and Spacy model did run faster (1min37 vs 1min53)

2022-06-21 07:37 UTC, nicolasdalsass commented
I think this PR is a good first step, however I need to mention a couple things : 

- In no way should we accept that some features are locked behind editing the plugin in dev mode. If it's not available natively, we should consider we don't support it. I think there's a missed opportunity of nicely weaving the download model macro in the new version to support extra languages and model, instead of just removing it.

- While there's indeed an appreciable speed gain running this new version, I suppose it's mainly due to the bumping of lib version and not much else, meaning there's still something to explore regarding parallelized exec. I tested the code, and running the recipe uses 100% of a single core, which quite frankly is not great. We should aim to use 100% of the available resources, and trust users to have a correct setup using cgroups to not make their servers explode.

So I'm ok with merging this PR since imo it's a net improvement over the existing situation (modulo the little comments I made), but I think we should be able to go sensibly further in the future.

2022-06-21 07:37 UTC, nicolasdalsass requested changes

2022-06-21 07:37 UTC, nicolasdalsass commented on code-env/python/spec/requirements.txt
> +spacy[ja]==3.3.0
```suggestion
spacy[ja]==3.3.0
tokenizers==0.10.3; python_version == '3.6'
sudachipy==0.5.4; python_version == '3.6'
```

Support for py3.6

2022-06-21 07:37 UTC, nicolasdalsass commented on custom-recipes/named-entity-recognition-extract/recipe.json
> +            "description": "List of supported languages (May need to edit requirements.txt)",
I don't think a plugin should reference files which are not exposed to the user in the first place. We can't expect everyone to be admin, put the plugin in dev mode, and go ham on it.

So imo either we provide an in-plugin way to do this, either we don't mention it.

2022-06-21 07:37 UTC, nicolasdalsass commented on custom-recipes/named-entity-recognition-extract/recipe.json
> +            "description": "Additional models can be added in the resources_init.py script",
Ditto

2022-06-21 09:40 UTC, nicolasdalsass commented
Cf https://github.com/dataiku/dss-plugin-nlp-named-entity-recognition/pull/11 because I was curious :-D

2022-07-27 07:42 UTC, nicolasdalsass approved these changes

2022-07-27 07:44 UTC, merged